#include <asm-generic/socket.h>
#include <assert.h>
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/poll.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <fcntl.h>
#include <vector>
#include <poll.h>
#include <iostream>

#define MAX_BUF_SIZE 64 * 1024

void die(const char* err_str) {
    fprintf(stderr, "%s\n", err_str);
    exit(EXIT_FAILURE);
}

static void set_fd_nonblock(int fd) {
    int flags = fcntl(fd, F_GETFL, 0);
    flags |= O_NONBLOCK;
    fcntl(fd, F_SETFL, flags);
}

void buf_append(std::vector<uint8_t>& buf, const uint8_t* data, size_t n) {
   buf.insert(buf.end(), data, data + n);
}

void buf_consume(std::vector<uint8_t>& buf,size_t n) {
   buf.erase(buf.begin(), buf.begin() + n);
}


/**
 * while running:
 *      want_read  = [...]
 *      want_write = [...]
 *      can_read, can_write = wait_for_readiness(want_read, want_write) # blocks until there is one r/w conn.
 *      for fd in can_read:
 *          data = read_nb(fd) # non blocking
 *          handle_data(fd, data) # application logic w/o IO
 *      for fd in can_write:
 *          data = pending_data(fd) # data to write produced by application
 *          write_nb(fd, data) # non blocking - append to buffer
 */

struct Conn {
    int fd          = -1;

    bool want_read  = false;
    bool want_write = false;
    bool want_close = false;

    std::vector<uint8_t> incoming; // data to be parsed by the app
    std::vector<uint8_t> outgoing; // responses generated by the app

    /**
     * since reads are now non-blocking, we can't wait for n bytes while parsing the protocol, so read_full is irrelevant
     * at each loop iteration, if the socket is ready to read:
     * 1. do a non-blocking read
     * 2. add new data to Conn::incoming
     * 3. try to parse the current buffer - if there isn't enough data -> do nothing
     * 4. process the parsed message
     * 5. remove the message from Conn::incoming
     *
     *
     * why buffer the outgoing data?
     * since writes are non-blocking, we can't write to sockets at will, data is only written when the socket is ready.
     * large response may take multiple iterations to complete so the response is buffered in Conn::outgoing
     */
};


static Conn* handle_accept(int fd) {
    struct sockaddr_in client_addr = {};
    socklen_t addr_len = sizeof(client_addr);
    int conn_fd =  accept(fd, (struct sockaddr *) &client_addr, &addr_len);
    if(conn_fd < 0) {
        return NULL;
    }

    set_fd_nonblock(conn_fd);

    Conn* conn = new Conn;
    conn->fd = conn_fd;
    conn->want_read = true; // ready for 1st request
    return conn;
}

// process 1 request if there is enough data
bool try_one_request(Conn* conn) {
    if(conn->incoming.size() < 4) return false;

    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    if(len > MAX_BUF_SIZE) {
        conn->want_close = true;
        return false;
    }

    if(4 + len > conn->incoming.size()) return false; // -> want_read

    const uint8_t* request = &conn->incoming[4];

    // 4. process message

    // generate response (we're echoing rn)
    buf_append(conn->outgoing, (const uint8_t *)&len, 4);
    buf_append(conn->outgoing, request, len);

    // remove message from Conn::incoming
    buf_consume(conn->incoming, len + 4);

    return true;
}

static void handle_read(Conn* conn) {
    // 1. do non blocking read
    uint8_t buf[MAX_BUF_SIZE];
    ssize_t rv = read(conn->fd, buf, MAX_BUF_SIZE);
    std::cout << "byets read: " << rv << '\n';
    if(rv <= 0) {
        conn->want_close = true;
        return;
    }
    buf[rv] = '\0';

    // 2. append data to incoming buffer
    buf_append(conn->incoming, buf, rv);
    // 3. try to parse buffer
    // 4. process parsed message
    // 5. remove message from Conn::incoming
    try_one_request(conn);

    if(conn->outgoing.size() > 0){ // has a response
        conn->want_write = true;
        conn->want_read = false;
    } // else: want_read
}

static void handle_write(Conn* conn) {
    assert(conn->outgoing.size() > 0);
    ssize_t rv = write(conn->fd, conn->outgoing.data(), conn->outgoing.size());
    if(rv < 0) {
        conn->want_close = true;
        return;
    }

    buf_consume(conn->outgoing, (size_t)rv);
    if(conn->outgoing.size() == 0) { // all data written
        conn->want_read = true;
        conn->want_write = false;
    } // else: want_write = true
}

int main() {
    int fd = socket(AF_INET, SOCK_STREAM, 0);

    set_fd_nonblock(fd);
    // allow socket to reuse address after restart
    int allow_reuse = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &allow_reuse, sizeof(allow_reuse));

    struct sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234); // port: 1234
    addr.sin_addr.s_addr = htonl(0); // 0.0.0.0
    int rv = bind(fd, (const struct sockaddr*)&addr, sizeof(addr));
    if(rv) { die("bind()"); }

    rv = listen(fd, SOMAXCONN);
    if(rv) { die("listen()"); }

    // map of all client connections, keyed by fd
    std::vector<Conn* > fd2conn;

    /**
     * struct pollfd {
     *  int fd;
     *  short events; // request: read, write, both?
     *  short revents; // returned: can_read? can_write?
     * }
     * int poll(struct pollfd* pfds, nfds_t nfds, int timeout)
     * nfds -> sizeof pfds array
     * pollfd::events:
     *  POLLIN  -> want_read
     *  POLLOUT -> want_write
     *  POLLERR -> err
     * pollfd::revents is returned by poll(). It uses the same set of flags to indicate whether the fd is in the can_read or can_write list.
     */
    std::vector<struct pollfd> poll_args;
    while(true) {
        // set up poll arguments
        // clear list for this iteration
        poll_args.clear();

        // put listening socket (server fd) at first position
        struct pollfd pfd = { .fd = fd, .events = POLLIN, .revents = 0 };
        poll_args.push_back(pfd);

        for(Conn* c : fd2conn) {
            if(!c) continue;

            struct pollfd conn_pfd = { c->fd, POLLERR, 0 };

            // poll() flags from the application's intent
            if(c->want_read) {
                conn_pfd.events |= POLLIN;
            }

            if(c->want_write) {
                conn_pfd.events |= POLLOUT;
            }
            poll_args.push_back(conn_pfd);
        }

        // wait for readiness
        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        if(rv < 0 && errno == EINTR) continue;
        if(rv < 0) die("poll()");

        // handle the listening socket (server fd)
        if(poll_args[0].revents) {
            if(Conn* conn = handle_accept(fd)) {
                if(fd2conn.size() <= (size_t)conn->fd) {
                    fd2conn.resize(conn->fd + 1);
                }
                fd2conn[conn->fd] = conn;
            }
        }

        for(size_t i = 1; i < poll_args.size(); i++) {
            uint32_t ready = poll_args[i].revents;
            Conn* conn = fd2conn[poll_args[i].fd];
            if(ready & POLLIN) {
                handle_read(conn); // application logic
            } else if (ready & POLLOUT) {
               handle_write(conn); // application logic
            }

            if ((ready & POLLERR) || conn->want_close) {
                close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }


    }

}
