#include <asm-generic/socket.h>
#include <string>
#include <assert.h>
#include <cerrno>
#include <cstddef>
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/poll.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <fcntl.h>
#include <arpa/inet.h>
#include <vector>
#include <poll.h>
#include <map>

#define MAX_BUF_SIZE 64 * 1024
#define MAX_ARGS 8

// forward declarations
struct Conn;
void handle_read(Conn* conn);
void handle_write(Conn* conn);

static std::map<std::string, std::string> global_map_replace;
struct Response {
    uint32_t status = 0;
    std::vector<uint8_t> data;
};

void die(const char* err_str) {
    fprintf(stderr, "%s\n", err_str);
    exit(EXIT_FAILURE);
}
void msg(const char* msg){
    fprintf(stderr, "%s\n", msg);
}

static void set_fd_nonblock(int fd) {
    int flags = fcntl(fd, F_GETFL, 0);
    flags |= O_NONBLOCK;
    fcntl(fd, F_SETFL, flags);
}

// TODO: pick a better data structure since appending is fine but erase is not
void buf_append(std::vector<uint8_t>& buf, const uint8_t* data, size_t n) {
   buf.insert(buf.end(), data, data + n);
}

void buf_consume(std::vector<uint8_t>& buf,size_t n) {
   buf.erase(buf.begin(), buf.begin() + n);
}

// int* &p = reference to int* just so we can increment the value
bool read_u32(const uint8_t* &start, const uint8_t* end, uint32_t& out) {
    if(start + 4 > end) return false;
    memcpy(&out, start, 4);
    start += 4;
    return true;
}

bool read_str(const uint8_t*& start, const uint8_t* end, uint32_t len, std::string& out) {
    if(start + len > end) return false;
    out.assign(start, start + len);
    start += len;
    return true;
}



struct Conn {
    int fd          = -1;

    bool want_read  = false;
    bool want_write = false;
    bool want_close = false;

    std::vector<uint8_t> incoming; // data to be parsed by the app
    std::vector<uint8_t> outgoing; // responses generated by the app

    /**
     * since reads are now non-blocking, we can't wait for n bytes while parsing the protocol, so read_full is irrelevant
     * at each loop iteration, if the socket is ready to read:
     * 1. do a non-blocking read
     * 2. add new data to Conn::incoming
     * 3. try to parse the current buffer - if there isn't enough data -> do nothing
     * 4. process the parsed message
     * 5. remove the message from Conn::incoming
     *
     *
     * why buffer the outgoing data?
     * since writes are non-blocking, we can't write to sockets at will, data is only written when the socket is ready.
     * large response may take multiple iterations to complete so the response is buffered in Conn::outgoing
     */
};

/**
 * 1. create socket
 * 2. bind socket to port
 * 3. listen
 * while running:
 *      want_read  = [...]
 *      want_write = [...]
 *      can_read, can_write = wait_for_readiness(want_read, want_write) # blocks until there is one r/w conn.
 *      for fd in can_read:
 *          data = read_nb(fd) # non blocking
 *          handle_data(fd, data) # application logic w/o IO
 *      for fd in can_write:
 *          data = pending_data(fd) # data to write produced by application
 *          write_nb(fd, data) # non blocking - append to buffer
 */
static Conn* handle_accept(int fd) {
    struct sockaddr_in client_addr = {};
    socklen_t len = sizeof(client_addr);
    int conn_fd = accept(fd, (struct sockaddr *)&client_addr, &len);
    if(conn_fd < 0) return NULL;

    set_fd_nonblock(conn_fd);
    printf("accepted connection from %s:%d\n", inet_ntoa(client_addr.sin_addr), ntohs(client_addr.sin_port));

    Conn* conn = new Conn();
    conn->fd = conn_fd;
    conn->want_read = true; // wait for first request
    return conn;
}

bool parse_request(const uint8_t* request, uint32_t len, std::vector<std::string>& out) {
    const uint8_t* start = request;
    const uint8_t* end   = request + len;

    uint32_t nargs = 0;
    if(read_u32(start, end, nargs) == false) return false;
    if(nargs > MAX_ARGS) return false;

    // 23GET3KEY
    while(out.size() < nargs) {
        uint32_t arg_len = 0;
        if(read_u32(start, end, arg_len) == false) return false;
        out.push_back(std::string());
        if(read_str(start, end, arg_len, out.back()) == false) return false;
    }
    if(start != end) return false; // had garbage
    return true;
}

// The handling is split into try_one_request(). If there is not enough data, it will do nothing until a future loop iteration with more data.
// TCP is a byte stream, so a single read() may contain a partial request
// or multiple requests. We first accumulate bytes into the input buffer,
// then try to parse complete requests. If a request is incomplete, we
// return and wait for the next poll() event instead of blocking.
// request protocol: [len][data of len bytes][len][data of len bytes]
static bool try_parse_request(Conn* conn){
    if(conn->incoming.size() < 4) return false;

    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    if(len > MAX_BUF_SIZE) {
        conn->want_close = true;
        return false;
    }

    if(4 + len > conn->incoming.size()) return false;

    const uint8_t* request = &conn->incoming[4];

    // request protocol:
    // [nargs][len1][arg1][len2][arg2]...[lenn][argn]
    // [21GET8abdullah][]
    std::vector<std::string> cmds;
    if(parse_request(request, len, cmds) == false) {
        conn->want_close = true;
        return false;
    }

    printf("cmd: ");
    for(const auto& cmd : cmds) printf("%s ", cmd.c_str());
    printf("\n");
    Response response;
    const auto execute_cmd = [&]() {
        if(cmds.size() == 2 && cmds[0] == "GET") {
            auto it = global_map_replace.find(cmds[1]);
            if(it == global_map_replace.end()) {
                response.status = -1;
                return;
            }
            const std::string& val = it->second;
            response.data.assign(val.begin(), val.end());
        } else if (cmds.size() == 3 && cmds[0] == "SET") {
            global_map_replace[cmds[1]].swap(cmds[2]);
        } else if (cmds.size() == 2 && cmds[0] == "DEL") {
            global_map_replace.erase(cmds[1]);
        } else {
            response.status = -1;
        }
    };
    execute_cmd();

    uint32_t resp_len = 4 + (uint32_t)response.data.size();
    buf_append(conn->outgoing, (const uint8_t *)&resp_len, 4);
    buf_append(conn->outgoing, (const uint8_t *)&response.status, 4);
    buf_append(conn->outgoing, response.data.data(), response.data.size());


    // remove the message from incoming
    buf_consume(conn->incoming, len + 4);

    return true;
}

void handle_read(Conn* conn) {
    // non blocking read
    uint8_t buf[MAX_BUF_SIZE];
    ssize_t count = read(conn->fd, buf, sizeof(buf));
    if(count < 0 && errno == EAGAIN) return;
    if(count < 0) {
        conn->want_close = true;
        return;
    }
    if(count == 0){
        if(conn->incoming.size() == 0) msg("client closed");
        else msg("unexpected EOF");
        conn->want_close = true;
        return;
    }

    // whatever data the client sends, we don't care just consume it
    buf_append(conn->incoming, buf, (size_t)count);

    //keep parsing requests until we can't anymore
    // [len][request][len][request]...in case client sends multiple requests at once
    // one read() can have more than 1 request
    while(try_parse_request(conn)) {}

    if(conn->outgoing.size() > 0) {
        conn->want_write = true;
        conn->want_read  = false;
        return handle_write(conn);
    }
}

void handle_write(Conn* conn) {
    assert(conn->outgoing.size() > 0);
    ssize_t count = write(conn->fd, conn->outgoing.data(), conn->outgoing.size());
    if(count < 0 && errno == EAGAIN) {
        return; // actually not ready yet
    }
    if(count < 0) {
        conn->want_close = true;
        return; // error
    }

    buf_consume(conn->outgoing,(size_t)count);
    if(conn->outgoing.size() == 0) {
        conn->want_read = true;
        conn->want_write = false;
    }
}

int main() {
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    if(!fd) die("socket()");

    int allow_port_reuse = 1;
    setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, &allow_port_reuse, sizeof(allow_port_reuse));

    set_fd_nonblock(fd);

    struct sockaddr_in addr = {};
    addr.sin_family = AF_INET;
    addr.sin_port = htons(1234);
    addr.sin_addr.s_addr = htonl(0);
    int rv = bind(fd, (const struct sockaddr *)&addr, (socklen_t)(sizeof(addr)));
    if(rv) { die("bind()"); }

    rv = listen(fd, SOMAXCONN);
    if(rv) { die("listen()"); }

    std::vector<Conn *> fd2conn;

    std::vector<struct pollfd> poll_args;
    /**
    * struct pollfd {
    *  int fd;
    *  short events; // request: read, write, both?
    *  short revents; // returned: can_read? can_write?
    * }
    * int poll(struct pollfd* pfds, nfds_t nfds, int timeout)
    * nfds -> sizeof pfds array
    * pollfd::events:
    *  POLLIN  -> want_readv i.e data is available to read
    *  POLLOUT -> want_write i.e data is available to write
    *  POLLERR -> err
    * basically, instead of being blocked when you call read()/write() we're guarunteed that fd is ready
    * events: request, revents -> response
    * pollfd::revents is returned by poll(). It uses the same set of flags to indicate whether the fd is in the can_read or can_write list.
    * suppose fd = 1, kernel waits for fd, client sends msg "hello" to fd 1, then fd_1.revents = POLLIN i.e i have data to read
    */
    while(true) {
        // phase 1: setup poll_args for this iteration
        poll_args.clear();

        // listening socket (the server waiting for new connections)
        poll_args.push_back(pollfd{ .fd = fd, .events = POLLIN, .revents = 0 });

        for(Conn* conn : fd2conn) {
            if(!conn) continue;

            struct pollfd conn_pfd = { .fd = conn->fd, .events = POLLERR, .revents = 0 };

            if(conn->want_read) {
                // wake me when this fd is readable
                conn_pfd.events |= POLLIN;
            }

            if(conn->want_write){
                conn_pfd.events |= POLLOUT;
            }

            poll_args.push_back(conn_pfd);
        }

        // wait for readiness
        int rv = poll(poll_args.data(), (nfds_t)poll_args.size(), -1);
        if(rv < 0 && errno == EINTR) continue;
        if(rv < 0) die("poll()");

        // phase 2: listen on the first socket
        if(poll_args[0].revents & POLLIN){
            printf("accepting connection\n");
            printf("current poll_args size: %zu\n", poll_args.size());
            if(Conn* conn = handle_accept(fd)) {
                if(fd2conn.size() <= (size_t)conn->fd) {
                    fd2conn.resize(conn->fd + 1);
                }
                fd2conn[conn->fd] = conn;
            }
        }

        for(size_t i = 1; i < poll_args.size(); ++i) {
            Conn* conn      = fd2conn[poll_args[i].fd];
            uint32_t ready  = poll_args[i].revents;
            if(ready & POLLIN){
                handle_read(conn);
            } else if (ready & POLLOUT) {
                handle_write(conn);
            }

            if((ready & POLLERR) || conn->want_close) {
                close(conn->fd);
                fd2conn[conn->fd] = NULL;
                delete conn;
            }
        }
    }

}
